---
name: SNMP-MibProxy
version: 1.0771
author:
  - 'Nito Martinez <nito@qindel.es>'
abstract: Simple pass_persist script for Net-SNMP
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Config::Properties::Simple: 0.14
  File::Path: 1.05
  File::Temp: 0
  IPC::Open2: 0
  Log::Dispatch::FileRotate: 0
  Log::Log4perl: 0
  Pod::Usage: 0
  Proc::ProcessTable: 0
  SNMP: 0
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  SNMP::MibProxy:
    file: lib/SNMP/MibProxy.pm
    version: 1.0771
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
